import Foundation
import Sparkle

/// Wraps Sparkle's standard updater so SwiftUI can trigger "Check for Updates…".
///
/// The updater reads `SUFeedURL` and `SUPublicEDKey` from Info.plist (set in `project.yml`).
/// Updates are EdDSA-signed with the key generated by Sparkle's `generate_keys`; no Apple
/// Developer ID is required (see README → Distribution).
@MainActor
final class UpdaterViewModel: ObservableObject {

    private let controller: SPUStandardUpdaterController

    /// Mirrors whether a manual check is currently allowed.
    @Published private(set) var canCheckForUpdates = true

    init() {
        // `startingUpdater: true` begins the periodic background check immediately.
        controller = SPUStandardUpdaterController(startingUpdater: true,
                                                  updaterDelegate: nil,
                                                  userDriverDelegate: nil)
        controller.updater.publisher(for: \.canCheckForUpdates)
            .receive(on: RunLoop.main)
            .assign(to: &$canCheckForUpdates)
    }

    /// User-initiated update check (from the popover menu).
    func checkForUpdates() {
        controller.checkForUpdates(nil)
    }

    var automaticallyChecksForUpdates: Bool {
        get { controller.updater.automaticallyChecksForUpdates }
        set { controller.updater.automaticallyChecksForUpdates = newValue }
    }
}
